# Generated by Django 5.2.9 on 2025-12-23 17:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(help_text='Xodimning ismi', max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(help_text='Xodimning familiyasi', max_length=100, verbose_name='Familiya')),
                ('email', models.EmailField(help_text='Xodimning elektron pochta manzili', max_length=100, verbose_name='Elektron pochta')),
                ('department', models.CharField(blank=True, help_text="Xodim ishlaydigan bo'lim nomi", max_length=100, null=True, verbose_name="Bo'lim")),
                ('position', models.CharField(blank=True, help_text='Xodimning lavozimi', max_length=100, null=True, verbose_name='Lavozim')),
                ('photo', models.ImageField(help_text='Xodimning rasmi', upload_to='faces/', verbose_name='Rasm')),
                ('face_encoding', models.TextField(blank=True, help_text="Xodimning yuz kodlash ma'lumotlari JSON formatida", null=True, verbose_name='Yuz kodlash')),
                ('is_active', models.BooleanField(default=True, help_text="Xodim faol yoki yo'qligini ko'rsatadi", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'attendance_employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of this attendance record', verbose_name='Sana')),
                ('check_in_time', models.TimeField(blank=True, help_text='Time when employee checked in', null=True, verbose_name='Kirish vaqti')),
                ('check_out_time', models.TimeField(blank=True, help_text='Time when employee checked out', null=True, verbose_name='Chiqish vaqti')),
                ('status', models.CharField(choices=[('present', 'Keldi (Present)'), ('late', 'Kechikdi (Late)'), ('absent', 'Kelmadi (Absent)'), ('half_day', 'Yarim Kun (half-day)'), ('on_leave', "Ta'tilda (On Leave)")], default='present', help_text='Attendance status', max_length=20, verbose_name='Holat (status)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance', null=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt (Created At)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti (Updated At)')),
                ('employee', models.ForeignKey(help_text='The employee this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomat (Attendance)',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'attendance_attendance',
                'ordering': ['-date', 'check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
